services:
  dashboard:
    image: ghcr.io/phudit-2547/chunimai-dashboard:latest
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TZ: Asia/Bangkok
    ports:
      - "3000:3000"
    networks:
      - scraper_net

networks:
  scraper_net:
    external: true
    name: chunimai_tracker
